### ISSUE TITLE
Edit layout (for both iOS and Android)

### ISSUE THREAD

**Issue by ghost** [4screens/brightcove-player-cordova-plugin#7]
Could you please provide some documentation on how to edit the layout for the player? I want to be able to override the current layout/styles from within either my angular code, or as a css class - no issue if this isn't possible. Just some direction on how to customize the look and feel would be great. I have attached an image of a panel I want to be able to display at the top, above the player.
![screen shot 2015-04-17 at 11 11 12 am](https://cloud.githubusercontent.com/assets/11052114/7194469/f8e2839c-e4f2-11e4-917a-b3fe6d7201f8.png)

**Comment by kostkobv** [comment]
You know, this plugin is based on Brightcove Player native(!!!) SDK, so that mean that whole player stuff is based on Objective C and Java code. You're not able to modify how player looks with CSS. 

The only way to change it is to make some changes to layout in Android and storyboard for iOS. I recommend to create a fork and try to change it in your Android Studio and XCode. Pull Requests are welcomed!
